package com.andrewdacenko.structures;

import java.util.Random;

public class DataGenerator {
    public static Random random = new Random(System.currentTimeMillis());

    public static Object[] generate() {
        boolean isMale = random.nextBoolean();

        return new Object[]{
                DataGenerator.generateName(isMale),
                "" + random.nextInt(999999),
                "" + (random.nextInt(5) + 1),
                isMale ? "male" : "female",
                countries[random.nextInt(countries.length)],
                DataGenerator.generateScores(random.nextInt(5) + 1)
        };
    }

    public static Object[][] generate(int size) {
        Object[][] records = new Object[size][];

        for (int i = 0; i < size; i++) {
            records[i] = DataGenerator.generate();
        }

        return records;
    }

    public static String generateName(boolean isMale) {
        String[] names = isMale ? maleNames : femaleNames;

        int nameIndex = random.nextInt(names.length);
        int lastIndex = random.nextInt(lastNames.length);

        return capitalize(names[nameIndex]) + " " + capitalize(lastNames[lastIndex]);
    }

    public static Scores generateScores(int disciplines) {
        Scores scores = new Scores();

        for (int i = 0; i < disciplines; i++) {
            scores.add(new Score(DataGenerator.generateScore()));
        }

        return scores;
    }

    public static Object[] generateScore() {
        return new Object[]{
                disciplineNames[random.nextInt(disciplineNames.length)],
                "" + (random.nextInt(5) + 1)
        };
    }

    public static String capitalize(String s) {
        if (s.length() == 0) return s;
        return s.substring(0, 1).toUpperCase() + s.substring(1).toLowerCase();
    }

    static String[] femaleNames = {
            "abigail",
            "addison",
            "alexa",
            "alexis",
            "alice",
            "alicia",
            "allison",
            "alma",
            "alyssa",
            "amanda",
            "amber",
            "amelia",
            "amy",
            "ana",
            "andrea",
            "anita",
            "ann",
            "anna",
            "anne",
            "annette",
            "annie",
            "april",
            "arianna",
            "arlene",
            "ashley",
            "aubree",
            "aubrey",
            "audrey",
            "ava",
            "avery",
            "beatrice",
            "becky",
            "bella",
            "bernice",
            "bertha",
            "bessie",
            "beth",
            "beverley",
            "beverly",
            "billie",
            "bobbie",
            "bonnie",
            "brandie",
            "brandy",
            "brianna",
            "brittany",
            "brooklyn",
            "camila",
            "candice",
            "carla",
            "carmen",
            "carole",
            "caroline",
            "carolyn",
            "carrie",
            "cassandra",
            "catherine",
            "cathy",
            "celina",
            "charlene",
            "charlotte",
            "cherly",
            "chloe",
            "christina",
            "christine",
            "christy",
            "cindy",
            "claire",
            "clara",
            "claudia",
            "colleen",
            "connie",
            "constance",
            "courtney",
            "crystal",
            "daisy",
            "dana",
            "danielle",
            "darlene",
            "dawn",
            "deann",
            "deanna",
            "debbie",
            "debra",
            "delores",
            "denise",
            "diana",
            "diane",
            "dianne",
            "dolores",
            "dora",
            "doris",
            "edith",
            "edna",
            "eileen",
            "elaine",
            "eleanor",
            "elizabeth",
            "ella",
            "ellen",
            "elsie",
            "emily",
            "emma",
            "erica",
            "erika",
            "erin",
            "esther",
            "ethel",
            "eva",
            "evelyn",
            "felecia",
            "felicia",
            "florence",
            "frances",
            "gabriella",
            "gail",
            "genesis",
            "georgia",
            "gertrude",
            "gina",
            "gladys",
            "glenda",
            "gloria",
            "grace",
            "gwendolyn",
            "hailey",
            "hannah",
            "harper",
            "hazel",
            "heather",
            "heidi",
            "herminia",
            "hilda",
            "holly",
            "ida",
            "irene",
            "irma",
            "isabella",
            "isobel",
            "jackie",
            "jacqueline",
            "jamie",
            "jane",
            "janet",
            "janice",
            "jean",
            "jeanette",
            "jeanne",
            "jennie",
            "jennifer",
            "jenny",
            "jessica",
            "jessie",
            "jill",
            "jo",
            "joan",
            "joann",
            "joanne",
            "josephine",
            "joy",
            "joyce",
            "juanita",
            "judith",
            "judy",
            "julia",
            "julie",
            "june",
            "katherine",
            "kathryn",
            "kathy",
            "katie",
            "katrina",
            "kay",
            "kaylee",
            "kelly",
            "kenzi",
            "kim",
            "kitty",
            "krin",
            "kristen",
            "kristin",
            "kristina",
            "kylie",
            "lauren",
            "laurie",
            "layla",
            "leah",
            "lena",
            "leona",
            "lesa",
            "leslie",
            "leta",
            "letitia",
            "lillian",
            "lillie",
            "lily",
            "linda",
            "lisa",
            "lois",
            "loretta",
            "lori",
            "lorraine",
            "louella",
            "louise",
            "lucille",
            "lucy",
            "lydia",
            "lynn",
            "mabel",
            "madison",
            "mae",
            "marcia",
            "margie",
            "marian",
            "marie",
            "marilyn",
            "marion",
            "marjorie",
            "marlene",
            "marsha",
            "martha",
            "mary",
            "mattie",
            "maureen",
            "maxine",
            "megan",
            "meghan",
            "melanie",
            "melinda",
            "melissa",
            "mia",
            "michele",
            "michelle",
            "mildred",
            "minnie",
            "miriam",
            "misty",
            "monica",
            "myrtle",
            "naomi",
            "natalie",
            "nellie",
            "nevaeh",
            "nicole",
            "nina",
            "noelle",
            "nora",
            "norma",
            "olivia",
            "pamela",
            "patsy",
            "paula",
            "pauline",
            "pearl",
            "peggy",
            "penny",
            "peyton",
            "phyllis",
            "priscilla",
            "rachel",
            "ramona",
            "rebecca",
            "regina",
            "renee",
            "rhonda",
            "riley",
            "rita",
            "roberta",
            "robin",
            "rosa",
            "rose",
            "rosemary",
            "ruby",
            "sally",
            "samantha",
            "sandra",
            "sara",
            "sarah",
            "savannah",
            "scarlett",
            "serenity",
            "shannon",
            "sharlene",
            "sheila",
            "shelly",
            "sherri",
            "sherry",
            "sofia",
            "sonia",
            "sophia",
            "sophie",
            "stacey",
            "stacy",
            "stella",
            "stephanie",
            "sue",
            "susan",
            "suzanne",
            "sylvia",
            "tamara",
            "tammy",
            "tanya",
            "tara",
            "taylor",
            "teresa",
            "terra",
            "terri",
            "terry",
            "theresa",
            "tiffany",
            "tina",
            "toni",
            "tonya",
            "tracey",
            "tracy",
            "valerie",
            "vanessa",
            "vera",
            "veronica",
            "vicki",
            "vickie",
            "victoria",
            "violet",
            "vivan",
            "wanda",
            "wendy",
            "willie",
            "wilma",
            "yolanda",
            "yvonne",
            "zoe",
            "zoey"
    };

    static String[] maleNames = {
            "aaron",
            "adam",
            "adrian",
            "aiden",
            "alan",
            "albert",
            "alberto",
            "alex",
            "alexander",
            "alfred",
            "alfredo",
            "allan",
            "allen",
            "alvin",
            "andre",
            "andrew",
            "andy",
            "angel",
            "anthony",
            "antonio",
            "armando",
            "arnold",
            "arron",
            "arthur",
            "austin",
            "barry",
            "ben",
            "benjamin",
            "bernard",
            "bill",
            "billy",
            "bob",
            "bobby",
            "brad",
            "bradley",
            "brandon",
            "brayden",
            "brennan",
            "brent",
            "brett",
            "brian",
            "bruce",
            "bryan",
            "byron",
            "caleb",
            "calvin",
            "cameron",
            "carl",
            "carlos",
            "carter",
            "cecil",
            "chad",
            "charles",
            "charlie",
            "chester",
            "chris",
            "christian",
            "christopher",
            "clarence",
            "claude",
            "clayton",
            "clifford",
            "clifton",
            "clinton",
            "clyde",
            "cody",
            "connor",
            "corey",
            "cory",
            "craig",
            "curtis",
            "dale",
            "dan",
            "daniel",
            "danny",
            "darrell",
            "darren",
            "darryl",
            "daryl",
            "dave",
            "david",
            "dean",
            "dennis",
            "derek",
            "derrick",
            "devon",
            "don",
            "donald",
            "douglas",
            "duane",
            "dustin",
            "dwayne",
            "dwight",
            "dylan",
            "earl",
            "eddie",
            "edgar",
            "eduardo",
            "edward",
            "edwin",
            "eli",
            "elijah",
            "elmer",
            "enrique",
            "eric",
            "erik",
            "ernest",
            "ethan",
            "eugene",
            "evan",
            "everett",
            "felix",
            "fernando",
            "flenn",
            "floyd",
            "francis",
            "francisco",
            "frank",
            "franklin",
            "fred",
            "freddie",
            "frederick",
            "gabe",
            "gabriel",
            "gary",
            "gavin",
            "gene",
            "george",
            "gerald",
            "gilbert",
            "glen",
            "gordon",
            "greg",
            "gregory",
            "guy",
            "harold",
            "harry",
            "harvey",
            "hector",
            "henry",
            "herbert",
            "herman",
            "howard",
            "hugh",
            "hunter",
            "ian",
            "isaac",
            "isaiah",
            "ivan",
            "jack",
            "jackson",
            "jacob",
            "james",
            "jamie",
            "jar",
            "jared",
            "jason",
            "javier",
            "jayden",
            "jeff",
            "jeffery",
            "jeffrey",
            "jeremiah",
            "jeremy",
            "jerome",
            "jerry",
            "jesse",
            "jessie",
            "jesus",
            "jim",
            "jimmie",
            "jimmy",
            "joe",
            "joel",
            "john",
            "johnni",
            "johnny",
            "jon",
            "jonathan",
            "jordan",
            "jorge",
            "jose",
            "joseph",
            "joshua",
            "juan",
            "judd",
            "julian",
            "julio",
            "justin",
            "karl",
            "keith",
            "kelly",
            "ken",
            "kenneth",
            "kent",
            "kevin",
            "kirk",
            "kurt",
            "kyle",
            "lance",
            "landon",
            "larry",
            "lawrence",
            "lee",
            "leo",
            "leon",
            "leonard",
            "leroy",
            "leslie",
            "lester",
            "levi",
            "lewis",
            "liam",
            "lloyd",
            "logan",
            "lonnie",
            "louis",
            "lucas",
            "luis",
            "luke",
            "manuel",
            "marc",
            "marcus",
            "mario",
            "marion",
            "mark",
            "marshall",
            "martin",
            "marvin",
            "mason",
            "mathew",
            "matthew",
            "maurice",
            "max",
            "melvin",
            "michael",
            "micheal",
            "miguel",
            "mike",
            "milton",
            "mitchell",
            "morris",
            "nathan",
            "nathaniel",
            "neil",
            "nelson",
            "nicholas",
            "noah",
            "norman",
            "oscar",
            "owen",
            "pat",
            "patrick",
            "paul",
            "pedro",
            "perry",
            "peter",
            "philip",
            "phillip",
            "rafael",
            "ralph",
            "ramon",
            "randall",
            "randy",
            "raul",
            "ray",
            "raymond",
            "reginald",
            "rene",
            "ricardo",
            "richard",
            "rick",
            "ricky",
            "ritthy",
            "robert",
            "roberto",
            "rodney",
            "roger",
            "roland",
            "ron",
            "ronald",
            "ronnie",
            "ross",
            "roy",
            "ruben",
            "russell",
            "ryan",
            "salvador",
            "same",
            "samuel",
            "scott",
            "sean",
            "sebastian",
            "sergio",
            "seth",
            "shane",
            "shawn",
            "soham",
            "stanley",
            "stephen",
            "steve",
            "steven",
            "ted",
            "terrance",
            "terrence",
            "terry",
            "theodore",
            "thomas",
            "tim",
            "timmothy",
            "todd",
            "tom",
            "tommy",
            "tomothy",
            "tony",
            "tracy",
            "travis",
            "tristan",
            "troy",
            "tyler",
            "tyrone",
            "vernon",
            "victor",
            "vincent",
            "virgil",
            "wade",
            "wallace",
            "walter",
            "warren",
            "wayne",
            "wesley",
            "willard",
            "william",
            "willie",
            "wyatt",
            "zachary",
            "zack"
    };

    static String[] lastNames = {
            "adams",
            "alexander",
            "allen",
            "alvarez",
            "anderson",
            "andrews",
            "armstrong",
            "arnold",
            "austin",
            "bailey",
            "baker",
            "banks",
            "barnes",
            "barnett",
            "barrett",
            "bates",
            "beck",
            "bell",
            "bennett",
            "berry",
            "bishop",
            "black",
            "bowman",
            "boyd",
            "bradley",
            "brewer",
            "brooks",
            "brown",
            "bryant",
            "burke",
            "burns",
            "burton",
            "butler",
            "byrd",
            "caldwell",
            "campbell",
            "carlson",
            "carpenter",
            "carr",
            "carroll",
            "carter",
            "castillo",
            "castro",
            "chambers",
            "chapman",
            "chavez",
            "clark",
            "cole",
            "coleman",
            "collins",
            "cook",
            "cooper",
            "cox",
            "craig",
            "crawford",
            "cruz",
            "cunningham",
            "curtis",
            "daniels",
            "davidson",
            "davis",
            "day",
            "dean",
            "diaz",
            "dixon",
            "douglas",
            "duncan",
            "dunn",
            "edwards",
            "elliott",
            "ellis",
            "evans",
            "ferguson",
            "fernandez",
            "fields",
            "fisher",
            "fleming",
            "fletcher",
            "flores",
            "ford",
            "foster",
            "fowler",
            "fox",
            "franklin",
            "frazier",
            "freeman",
            "fuller",
            "garcia",
            "gardner",
            "garrett",
            "garza",
            "george",
            "gibson",
            "gilbert",
            "gomez",
            "gonzales",
            "gonzalez",
            "gordon",
            "graham",
            "grant",
            "graves",
            "gray",
            "green",
            "gregory",
            "griffin",
            "gutierrez",
            "hale",
            "hall",
            "hamilton",
            "hansen",
            "hanson",
            "harper",
            "harris",
            "harrison",
            "hart",
            "harvey",
            "hawkins",
            "hayes",
            "henderson",
            "henry",
            "hernandez",
            "herrera",
            "hicks",
            "hill",
            "hoffman",
            "holland",
            "holmes",
            "holt",
            "hopkins",
            "horton",
            "howard",
            "howell",
            "hudson",
            "hughes",
            "hunt",
            "hunter",
            "jackson",
            "jacobs",
            "james",
            "jenkins",
            "jennings",
            "jensen",
            "jimenez",
            "johnson",
            "johnston",
            "jones",
            "jordan",
            "kelley",
            "kelly",
            "kennedy",
            "kim",
            "king",
            "knight",
            "kuhn",
            "lambert",
            "lane",
            "larson",
            "lawrence",
            "lawson",
            "lee",
            "lewis",
            "little",
            "long",
            "lopez",
            "lowe",
            "lucas",
            "lynch",
            "marshall",
            "martin",
            "martinez",
            "mason",
            "matthews",
            "may",
            "mccoy",
            "mcdonalid",
            "mckinney",
            "medina",
            "mendoza",
            "meyer",
            "miles",
            "miller",
            "mills",
            "mitchell",
            "mitchelle",
            "montgomery",
            "moore",
            "morales",
            "moreno",
            "morgan",
            "morris",
            "morrison",
            "murphy",
            "murray",
            "myers",
            "neal",
            "nelson",
            "newman",
            "nguyen",
            "nichols",
            "obrien",
            "oliver",
            "olson",
            "ortiz",
            "owens",
            "palmer",
            "parker",
            "patterson",
            "payne",
            "pearson",
            "peck",
            "pena",
            "perez",
            "perkins",
            "perry",
            "peters",
            "peterson",
            "phillips",
            "pierce",
            "porter",
            "powell",
            "prescott",
            "price",
            "ramirez",
            "ramos",
            "ray",
            "reed",
            "reid",
            "reyes",
            "reynolds",
            "rhodes",
            "rice",
            "richards",
            "richardson",
            "riley",
            "rivera",
            "roberts",
            "robertson",
            "robinson",
            "rodriguez",
            "rodriquez",
            "rogers",
            "romero",
            "rose",
            "ross",
            "ruiz",
            "russell",
            "ryan",
            "sanchez",
            "sanders",
            "schmidt",
            "scott",
            "shaw",
            "shelton",
            "silva",
            "simmmons",
            "simmons",
            "simpson",
            "sims",
            "smith",
            "snyder",
            "soto",
            "spencer",
            "stanley",
            "steeves ",
            "stephens",
            "stevens",
            "steward",
            "stewart",
            "stone",
            "sullivan",
            "sutton",
            "taylor",
            "terry",
            "thomas",
            "thompson",
            "torres",
            "tucker",
            "turner",
            "vargas",
            "vasquez",
            "wade",
            "wagner",
            "walker",
            "wallace",
            "walters",
            "ward",
            "warren",
            "washington",
            "watkins",
            "watson",
            "watts",
            "weaver",
            "webb",
            "welch",
            "wells",
            "west",
            "wheeler",
            "white",
            "williams",
            "williamson",
            "willis",
            "wilson",
            "wood",
            "woods",
            "wright",
            "young"
    };

    public static String[] countries = {
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo, Republic of the Congo",
            "Congo, Democratic Republic of the Congo",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar (Burma)",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Korea",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "St. Kitts and Nevis",
            "St. Lucia",
            "St. Vincent and The Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "UK (United Kingdom)",
            "USA (United States of America)",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City (Holy See)",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe"
    };

    static String[] disciplineNames = {
            "African history",
            "American history",
            "Ancient history",
            "Australian history",
            "Asian history",
            "European history",
            "Economic history",
            "Environmental history",
            "Ancient Greek history",
            "Intellectual history",
            "Latin American history",
            "Modern history",
            "Political history",
            "Pre-Columbian era",
            "Ancient Roman history",
            "Russian history",
            "Scientific history",
            "Technological history",
            "World history",
            "Classics",
            "Languages",
            "Applied linguistics",
            "Computational linguistics",
            "Discourse analysis",
            "Etymology",
            "Grammar",
            "Historical linguistics",
            "History of linguistics",
            "Interlinguistics",
            "Language arts",
            "Morphology",
            "Philology",
            "Phonetics",
            "Phonology",
            "Pragmatics",
            "Semantics",
            "Semiotics",
            "Sociolinguistics",
            "Syntax",
            "Composition studies",
            "Rhetoric",
            "Usage",
            "Word usage",
            "Arts administration",
            "Music",
            "Dance",
            "Television",
            "Theatre",
            "Film",
            "Oral literature",
            "Animation",
            "Art",
            "Design",
            "Drawing",
            "Painting",
            "Filmmaking",
            "Performance art",
            "Photography",
            "Sculpture",
            "Video Art",
            "Industrial design",
            "Graphic design",
            "Fashion design",
            "Interior design",
            "Landscape design",
            "Decorative arts",
            "Culinary art",
            "Fine arts",
            "Mixed media",
            "Creative arts",
            "Art history",
            "Calligraphy",
            "Printmaking",
            "Studio art",
            "Meta-philosophy",
            "Metaphysics",
            "Epistemology",
            "Ethics",
            "Aesthetics",
            "Social philosophy",
            "Philosophical traditions and schools",
            "History of philosophy",
            "Logic",
            "Applied philosophy",
            "Abrahamic religions",
            "Indian religions",
            "East Asian religions",
            "Comparative religion",
            "Mythology",
            "Irreligion",
            "Biological anthropology",
            "Anthropological linguistics",
            "Cultural anthropology",
            "Linguistic anthropology",
            "Social anthropology",
            "Agricultural economics",
            "Anarchist economics",
            "Applied economics",
            "Behavioural economics",
            "Bioeconomics",
            "Complexity economics",
            "Computational economics",
            "Consumer economics",
            "Development economics",
            "Ecological economics",
            "Econometrics",
            "Economic geography",
            "Economic history",
            "Economic sociology",
            "Economic systems",
            "Energy economics",
            "Entrepreneurial economics",
            "Environmental economics",
            "Evolutionary economics",
            "Experimental economics",
            "Feminist economics",
            "Financial economics",
            "Financial econometrics",
            "Green economics",
            "Growth economics",
            "Human development theory",
            "Industrial organization",
            "Information economics",
            "Institutional economics",
            "International economics",
            "Islamic economics",
            "Labor economics",
            "Law and economics",
            "Macroeconomics",
            "Managerial economics",
            "Marxian economics",
            "Mathematical economics",
            "Microeconomics",
            "Monetary economics",
            "Neuroeconomics",
            "Participatory economics",
            "Political economy",
            "Public finance",
            "Public economics",
            "Real estate economics",
            "Resource economics",
            "Social choice theory",
            "Socialist economics",
            "Socioeconomics",
            "Transport economics",
            "Welfare economics",
            "Feminine psychology",
            "Gender studies",
            "Heterosexism",
            "Human sexual behavior",
            "Human sexuality",
            "Masculine psychology",
            "Men's studies",
            "Queer studies",
            "Sex education",
            "Sexology",
            "Women's studies",
            "Cartography",
            "Human geography",
            "Environmental geography",
            "Physical geography",
            "Regional geography",
            "Remote sensing",
            "American politics",
            "Canadian politics",
            "Civics",
            "Comparative politics",
            "European studies",
            "Geopolitics",
            "International relations",
            "International organizations",
            "Nationalism studies",
            "Peace and conflict studies",
            "Policy studies",
            "Political behavior",
            "Political culture",
            "Political economy",
            "Political history",
            "Political philosophy",
            "Psephology",
            "Public administration",
            "Public policy",
            "Social choice theory",
            "Abnormal psychology",
            "Applied psychology",
            "Asian psychology",
            "Biological psychology",
            "Black psychology",
            "Clinical psychology",
            "Clinical neuropsychology",
            "Cognitive psychology",
            "Community psychology",
            "Comparative psychology",
            "Conservation psychology",
            "Consumer psychology",
            "Counseling psychology",
            "Criminal psychology",
            "Cultural psychology",
            "Developmental psychology",
            "Differential psychology",
            "Ecological psychology",
            "Educational psychology",
            "Environmental psychology",
            "Evolutionary psychology",
            "Experimental psychology",
            "Group psychology",
            "Family psychology",
            "Feminine psychology",
            "Forensic psychology",
            "Forensic developmental psychology",
            "Health psychology",
            "Humanistic psychology",
            "Indigenous psychology",
            "Legal psychology",
            "Masculine psychology",
            "Mathematical psychology",
            "Media psychology",
            "Medical psychology",
            "Military psychology",
            "Moral psychology",
            "Music psychology",
            "Neuropsychology",
            "Occupational psychology",
            "Occupational health psychology",
            "Organizational psychology",
            "Parapsychology",
            "Pediatric psychology",
            "Pedology (children study)",
            "Personality psychology",
            "Phenomenology",
            "Political psychology",
            "Positive psychology",
            "Psychoanalysis",
            "Psychobiology",
            "Psychometrics",
            "Psychology of religion",
            "Psychopathology",
            "Psychophysics",
            "Quantitative psychology",
            "Rehabilitation psychology",
            "School psychology",
            "Social psychology",
            "Sport psychology",
            "Traffic psychology",
            "Transpersonal psychology",
            "Analytical sociology",
            "Applied sociology",
            "Architectural sociology",
            "Behavioral sociology",
            "Chinese sociology",
            "Collective behavior",
            "Community informatics",
            "Comparative sociology",
            "Conflict theory",
            "Critical sociology",
            "Cultural sociology",
            "Cultural studies",
            "Criminology",
            "Critical management studies",
            "Demography",
            "Digital sociology",
            "Dramaturgical sociology",
            "Economic sociology",
            "Educational sociology",
            "Empirical sociology",
            "Environmental sociology",
            "Evolutionary sociology",
            "Feminist sociology",
            "Figurational sociology",
            "Futures studies",
            "Historical sociology",
            "Human ecology",
            "Humanistic sociology",
            "Industrial sociology",
            "Interactionism",
            "Internet sociology",
            "Interpretive sociology",
            "Jealousy sociology",
            "Macrosociology",
            "Marxist sociology",
            "Mathematical sociology",
            "Medical sociology",
            "Mesosociology",
            "Microsociology",
            "Military sociology",
            "Natural resource sociology",
            "Organizational studies",
            "Phenomenological sociology",
            "Policy sociology",
            "Polish sociology",
            "Psychoanalytic sociology",
            "Science studies",
            "Sexology",
            "Social capital",
            "Social change",
            "Social conflict theory",
            "Social control",
            "Social economy",
            "Social philosophy",
            "Social psychology",
            "Social policy",
            "Social research",
            "Social transformation",
            "Sociology of aging",
            "Sociology of agriculture",
            "Sociology of art",
            "Sociology of autism",
            "Sociology of childhood",
            "Sociology of conflict",
            "Sociology of culture",
            "Sociology of cyberspace",
            "Sociology of deviance",
            "Sociology of development",
            "Sociology of disaster",
            "Sociology of education",
            "Sociology of emotions",
            "Sociology of fatherhood",
            "Sociology of film",
            "Sociology of finance",
            "Sociology of food",
            "Sociology of gender",
            "Sociology of generations",
            "Sociology of globalization",
            "Sociology of government",
            "Sociology of health and illness",
            "Sociology of human consciousness",
            "Sociology of immigration",
            "Sociology of knowledge",
            "Sociology of language",
            "Sociology of law",
            "Sociology of leisure",
            "Sociology of literature",
            "Sociology of markets",
            "Sociology of marriage",
            "Sociology of motherhood",
            "Sociology of music",
            "Sociology of natural resources",
            "Sociology of organizations",
            "Sociology of peace, war, and social conflict",
            "Sociology of punishment",
            "Sociology of race and ethnic relations",
            "Sociology of religion",
            "Sociology of risk",
            "Sociology of science",
            "Sociology of scientific knowledge",
            "Sociology of social change",
            "Sociology of social movements",
            "Sociology of space",
            "Sociology of sport",
            "Sociology of technology",
            "Sociology of terrorism",
            "Sociology of the body",
            "Sociology of the family",
            "Sociology of the history of science",
            "Sociology of the Internet",
            "Sociology of work",
            "Social theory",
            "Social stratification",
            "Sociological theory",
            "Sociobiology",
            "Sociocybernetics",
            "Sociolinguistics",
            "Sociomusicology",
            "Structural sociology",
            "Theoretical sociology",
            "Urban studies",
            "Victimology",
            "Visual sociology",
            "Aerobiology",
            "Anatomy",
            "Biochemistry",
            "Bioinformatics",
            "Biophysics",
            "Biotechnology",
            "Botany",
            "Cell biology",
            "Chronobiology",
            "Computational biology",
            "Cryobiology",
            "Developmental biology",
            "Ecology",
            "Genetics",
            "Endocrinology",
            "Evolutionary biology",
            "Histology",
            "Human biology",
            "Immunology",
            "Limnology",
            "Linnaean taxonomy",
            "Marine biology",
            "Mathematical biology",
            "Microbiology",
            "Molecular biology",
            "Mycology",
            "Nutrition",
            "Neuroscience",
            "Paleobiology",
            "Parasitology",
            "Pathology",
            "Physiology",
            "Systematics",
            "Systems biology",
            "Virology",
            "Xenobiology",
            "Zoology",
            "Agrochemistry",
            "Analytical chemistry",
            "Astrochemistry",
            "Atmospheric chemistry",
            "Biochemistry",
            "Chemical engineering",
            "Chemical biology",
            "Cheminformatics",
            "Computational chemistry",
            "Cosmochemistry",
            "Electrochemistry",
            "Environmental chemistry",
            "Femtochemistry",
            "Flavor",
            "Flow chemistry",
            "Geochemistry",
            "Green chemistry",
            "Histochemistry",
            "Hydrogenation",
            "Immunochemistry",
            "Inorganic chemistry",
            "Marine chemistry",
            "Mathematical chemistry",
            "Mechanochemistry",
            "Medicinal chemistry",
            "Molecular biology",
            "Molecular mechanics",
            "Nanotechnology",
            "Natural product chemistry",
            "Neurochemistry",
            "Oenology",
            "Organic chemistry",
            "Organometallic chemistry",
            "Petrochemistry",
            "Pharmacology",
            "Photochemistry",
            "Physical chemistry",
            "Physical organic chemistry",
            "Phytochemistry",
            "Polymer chemistry",
            "Quantum chemistry",
            "Radiochemistry",
            "Solid-state chemistry",
            "Sonochemistry",
            "Supramolecular chemistry",
            "Surface chemistry",
            "Synthetic chemistry",
            "Theoretical chemistry",
            "Thermochemistry",
            "Acoustics",
            "Applied Physics",
            "Astrophysics",
            "Atomic, molecular, and optical physics",
            "Biophysics",
            "Computational physics",
            "Condensed matter physics",
            "Cryogenics",
            "Electromagnetism",
            "Elementary particle physics",
            "Fluid dynamics",
            "Geophysics",
            "Mathematical physics",
            "Medical physics",
            "Mechanics",
            "Molecular physics",
            "Newtonian dynamics",
            "Nuclear physics",
            "Optics",
            "Plasma physics",
            "Quantum physics",
            "Solid mechanics",
            "Solid state physics",
            "Statistical mechanics",
            "Theoretical physics",
            "Thermodynamics",
            "Vehicle dynamics",
            "Edaphology",
            "Environmental science",
            "Environmental chemistry",
            "Gemology",
            "Geodesy",
            "Geography",
            "Geology",
            "Geochemistry",
            "Geomorphology",
            "Geophysics",
            "Glaciology",
            "Hydrogeology",
            "Hydrology",
            "Meteorology",
            "Mineralogy",
            "Oceanography",
            "Pedology",
            "Paleontology",
            "Planetary science",
            "Sedimentology",
            "Soil science",
            "Speleology",
            "Tectonics",
            "Volcanology",
            "Astrobiology",
            "Astronomy",
            "Astrophysics",
            "Planetary science",
            "Statistics",
            "Approximation theory",
            "Numerical analysis",
            "Operations research",
            "Dynamical systems",
            "Mathematical physics",
            "Theory of computation",
            "Information theory",
            "Cryptography",
            "Combinatorics",
            "Graph theory",
            "Game theory",
            "Algebra",
            "Analysis",
            "Probability theory",
            "Geometry",
            "Number theory",
            "Logic",
            "Theory of computation",
            "VLSI design",
            "Operating systems",
            "Algorithms",
            "Data structures",
            "Computer architecture",
            "Computer communications (networks)",
            "Computer security",
            "Distributed computing",
            "Parallel computing",
            "Quantum computing",
            "Computer graphics",
            "Software engineering",
            "Programming languages",
            "Human-computer interaction",
            "Information science",
            "Artificial intelligence",
            "Mathematics",
            "Social sciences",
            "Mathematical logic",
            "Philosophical logic",
            "Logic in computer science",
            "Computational statistics",
            "Design of experiments",
            "Sample Survey",
            "Statistical modelling",
            "Statistical theory",
            "Network Science",
            "Chaos theory",
            "Conceptual systems",
            "Complex systems",
            "Complex system",
            "Cybernetics",
            "Control theory",
            "Operations research",
            "Systems biology",
            "System dynamics",
            "Systems ecology",
            "Systems engineering",
            "Systems theory in anthropology",
            "Systems psychology",
            "Systems theory",
            "Agroecology",
            "Agronomy",
            "Animal husbandry",
            "Agrology",
            "Entomology",
            "Agricultural economics",
            "Agricultural engineering",
            "Aquaculture",
            "Enology",
            "Food science",
            "Horticulture",
            "Hydrology",
            "Pedology (soil study)",
            "Plant science",
            "Viticulture",
            "Architecture",
            "Architectural analytics",
            "Historic preservation",
            "Interior design",
            "Landscape architecture",
            "Landscape design",
            "Urban planning",
            "Visual communication",
            "Industrial design",
            "User experience design",
            "Fashion design",
            "Textile design",
            "Accounting scholarship",
            "Business administration",
            "Business analysis",
            "Business ethics",
            "Business law",
            "E-Business",
            "Entrepreneurship",
            "Finance",
            "Industrial and labor relations",
            "Information systems",
            "Information technology",
            "International trade",
            "Marketing",
            "Operations management",
            "Purchasing",
            "Risk management",
            "Systems science",
            "Canon law",
            "Church history",
            "Hermeneutics",
            "Theology",
            "Comparative education",
            "Critical pedagogy",
            "Curriculum and instruction",
            "Educational leadership",
            "Educational philosophy",
            "Educational psychology",
            "Educational technology",
            "Distance education",
            "Bioengineering",
            "Catalysis",
            "Materials engineering",
            "Molecular engineering",
            "Nanotechnology",
            "Polymer engineering",
            "Process design",
            "Reaction engineering",
            "Thermodynamics",
            "Transport phenomena",
            "Coastal engineering",
            "Earthquake engineering",
            "Ecological engineering",
            "Environmental engineering",
            "Geotechnical engineering",
            "Hydraulic engineering",
            "Mining engineering",
            "Transportation engineering",
            "Structural engineering",
            "Structural mechanics",
            "Surveying",
            "Applied physics",
            "Computer engineering",
            "Computer science",
            "Control systems engineering",
            "Electronic engineering",
            "Engineering physics",
            "Information theory",
            "Mechatronics",
            "Power engineering",
            "Robotics",
            "Semiconductors",
            "Telecommunications engineering",
            "Quantum computing",
            "Biomaterials",
            "Ceramic engineering",
            "Crystallography",
            "Nanomaterials",
            "Photonics",
            "Physical Metallurgy",
            "Polymer engineering",
            "Polymer science",
            "Semiconductors",
            "Aerospace engineering",
            "Acoustical engineering",
            "Automotive engineering",
            "Biomedical engineering",
            "Continuum mechanics",
            "Fluid mechanics",
            "Heat transfer",
            "Industrial engineering",
            "Manufacturing engineering",
            "Marine engineering",
            "Mass transfer",
            "Mechatronics",
            "Nanoengineering",
            "Ocean engineering",
            "Optical engineering",
            "Robotics",
            "Thermodynamics",
            "Vehicle engineering",
            "Environmental management",
            "Environmental policy",
            "Recreation ecology",
            "Silviculture",
            "Sustainability studies",
            "Toxicology",
            "Consumer education",
            "Interior design",
            "Nutrition",
            "Textiles",
            "Biomechanics",
            "Sports coaching",
            "Dance",
            "Ergonomics",
            "Physical fitness",
            "Game design",
            "Exercise physiology",
            "Kinesiology",
            "Leisure studies",
            "Physical education",
            "Sociology of sport",
            "Sexology",
            "sportscasting",
            "Sport management",
            "Sport psychology",
            "Sports medicine",
            "Toy and amusement design",
            "Journalism",
            "Media studies",
            "Communication studies",
            "Legal management",
            "Administrative law",
            "Canon law",
            "Comparative law",
            "Constitutional law",
            "Competition law",
            "Criminal law",
            "Islamic law",
            "Jewish law",
            "Jurisprudence",
            "Civil law",
            "Procedural law",
            "Substantive law",
            "Archival science",
            "Bibliometrics",
            "Conservation science",
            "Informatics",
            "Information architecture",
            "Information science",
            "Museology",
            "Amphibious warfare",
            "Artillery",
            "Battlespace",
            "Campaigning",
            "Military engineering",
            "Doctrine",
            "Game theory",
            "Grand strategy",
            "Leadership",
            "Logistics",
            "Military history",
            "Military intelligence",
            "Military law",
            "Military medicine",
            "Organization",
            "Strategy",
            "Tactics",
            "Military weapons"
    };
}
